---
title: "W2"
author: Liying Wang
output: html_document
---

My potential questions for this auantitative research project as following:

<p> 1. What is the trend of research of social ineaulity in archaeolgy in the past decades? Is it popular in any particular time period?</p>

<p> 2. How often social inequality relates to culture contact? Especilally for European contact. Also, does any area show preference of such research, such as North America, Southeast Asia, Oceania, Afirca.</p>    

<p> 3. For the method, what is the relationship between the term "inequality" and other arhcaeological evidence, including burials, ceramics, post holes, or glass beads. </p>   

<P>In order to run the codes for my questions, I will use following two lbraries: 
<pre code>
library(devtools)
library(JSTORr)
</pre code>

The codes I need, for example:
<pre code>
# one word over time
JSTOR_1word(multiple_archives, "social inequality")
# two words over time
JSTOR_2words(multiple_archives, "culture contact", "inequality")
# correlation of words over time
JSTOR_2wordcor(multiple_archives, "culture contact", "inequality")</pre code>

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
